spring.application.name=pixelrig

server.port=8081

#sqlite
spring.datasource.url=jdbc:sqlite:productos_db.db
spring.datasource.driver-class-name=org.sqlite.JDBC

#hibernate 7
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true